### ISSUE TITLE
(Т) Неправильная работа с исключениями

### ISSUE THREAD

**Issue by ikit-mita** [Heidric/HomeWork2#3]
>a. Объекты модели __не должны выводить сообщения (об ошибках) на консоль__, а должны кидать исключения, которые обрабатываются на UI, где и выводится сообщение;
>b. Для описания различных исключительных ситуаций должны использоваться __отдельные__ типы исключений;

Метод Car.ChangeOwner не должен обрабатывать исключение, должен пропускать его на View где его и обработают.
Не используй тип Exception для этой ситуации, создай свой тип исключения

**Comment by Heidric** [comment]
Вроде бы исправил.
